// Auto-generated by Supabase MCP — do not edit by hand.
// Regenerate with: mcp__supabase__generate_typescript_types(project_id=vfnpmtqxrffppqajxxpb)
// or once Supabase CLI is linked: `supabase gen types typescript --linked > src/lib/database.types.ts`

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      tbl_agent_clicks: {
        Row: {
          agent_id: string
          anon_session_id: string | null
          click_id: string
          clicked_at: string
          source_raia_id: string | null
          user_id: string | null
        }
        Insert: {
          agent_id: string
          anon_session_id?: string | null
          click_id?: string
          clicked_at?: string
          source_raia_id?: string | null
          user_id?: string | null
        }
        Update: {
          agent_id?: string
          anon_session_id?: string | null
          click_id?: string
          clicked_at?: string
          source_raia_id?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      tbl_enquiries: {
        Row: {
          agent_id: string
          created_at: string
          enquirer_email: string
          enquirer_name: string
          enquirer_phone: string | null
          enquiry_id: string
          forwarded_at: string | null
          forwarded_response: Json | null
          message: string
          preferred_contact: string | null
          raia_id: string
          source: Json | null
          status: string
          submitted_at: string
          updated_at: string
          user_id: string | null
          viewing_request: Json | null
        }
        Insert: {
          agent_id: string
          created_at?: string
          enquirer_email: string
          enquirer_name: string
          enquirer_phone?: string | null
          enquiry_id?: string
          forwarded_at?: string | null
          forwarded_response?: Json | null
          message: string
          preferred_contact?: string | null
          raia_id: string
          source?: Json | null
          status?: string
          submitted_at?: string
          updated_at?: string
          user_id?: string | null
          viewing_request?: Json | null
        }
        Update: {
          agent_id?: string
          created_at?: string
          enquirer_email?: string
          enquirer_name?: string
          enquirer_phone?: string | null
          enquiry_id?: string
          forwarded_at?: string | null
          forwarded_response?: Json | null
          message?: string
          preferred_contact?: string | null
          raia_id?: string
          source?: Json | null
          status?: string
          submitted_at?: string
          updated_at?: string
          user_id?: string | null
          viewing_request?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "tbl_enquiries_agent_id_fkey"
            columns: ["agent_id"]
            isOneToOne: false
            referencedRelation: "tbl_raia_agent_registry"
            referencedColumns: ["agent_id"]
          },
        ]
      }
      tbl_external_raia_listings: {
        Row: {
          agent_card_url: string | null
          agent_id: string
          asking_price: number | null
          available_from: string | null
          bathrooms: number | null
          bedrooms: number | null
          building_number: string | null
          currency: string | null
          daily_rate: number | null
          development_name: string | null
          duplicate_of: string | null
          enquiry_endpoint: string | null
          external_id: string
          features: string[] | null
          first_seen_at: string
          floor: number | null
          floor_area_sqm: number | null
          furnishing: string | null
          headline: string | null
          is_new_build: boolean | null
          is_outlier: boolean
          jurisdiction: string | null
          jurisdiction_extensions: Json | null
          last_seen_at: string | null
          latitude: number | null
          listed_at: string | null
          listing_status: string | null
          location: unknown
          longitude: number | null
          marketing_description: string | null
          media: Json | null
          photo_count: number | null
          photo_url: string | null
          postcode_district: string | null
          postcode_full: string | null
          postcode_sector: string | null
          pricing_id: string | null
          property_type: string | null
          provenance: Json | null
          publish_from: string | null
          publish_until: string | null
          raia_id: string
          raia_schema_version: string | null
          rent_pcm: number | null
          service_type: string
          snapshot_version: number | null
          source: string
          street_name: string | null
          suburb: string | null
          synced_at: string
          total_floors: number | null
          un_locode: string | null
          visibility: string
          withdrawn_at: string | null
        }
        Insert: {
          agent_card_url?: string | null
          agent_id: string
          asking_price?: number | null
          available_from?: string | null
          bathrooms?: number | null
          bedrooms?: number | null
          building_number?: string | null
          currency?: string | null
          daily_rate?: number | null
          development_name?: string | null
          duplicate_of?: string | null
          enquiry_endpoint?: string | null
          external_id?: string
          features?: string[] | null
          first_seen_at?: string
          floor?: number | null
          floor_area_sqm?: number | null
          furnishing?: string | null
          headline?: string | null
          is_new_build?: boolean | null
          is_outlier?: boolean
          jurisdiction?: string | null
          jurisdiction_extensions?: Json | null
          last_seen_at?: string | null
          latitude?: number | null
          listed_at?: string | null
          listing_status?: string | null
          location?: unknown
          longitude?: number | null
          marketing_description?: string | null
          media?: Json | null
          photo_count?: number | null
          photo_url?: string | null
          postcode_district?: string | null
          postcode_full?: string | null
          postcode_sector?: string | null
          pricing_id?: string | null
          property_type?: string | null
          provenance?: Json | null
          publish_from?: string | null
          publish_until?: string | null
          raia_id: string
          raia_schema_version?: string | null
          rent_pcm?: number | null
          service_type: string
          snapshot_version?: number | null
          source?: string
          street_name?: string | null
          suburb?: string | null
          synced_at?: string
          total_floors?: number | null
          un_locode?: string | null
          visibility?: string
          withdrawn_at?: string | null
        }
        Update: {
          agent_card_url?: string | null
          agent_id?: string
          asking_price?: number | null
          available_from?: string | null
          bathrooms?: number | null
          bedrooms?: number | null
          building_number?: string | null
          currency?: string | null
          daily_rate?: number | null
          development_name?: string | null
          duplicate_of?: string | null
          enquiry_endpoint?: string | null
          external_id?: string
          features?: string[] | null
          first_seen_at?: string
          floor?: number | null
          floor_area_sqm?: number | null
          furnishing?: string | null
          headline?: string | null
          is_new_build?: boolean | null
          is_outlier?: boolean
          jurisdiction?: string | null
          jurisdiction_extensions?: Json | null
          last_seen_at?: string | null
          latitude?: number | null
          listed_at?: string | null
          listing_status?: string | null
          location?: unknown
          longitude?: number | null
          marketing_description?: string | null
          media?: Json | null
          photo_count?: number | null
          photo_url?: string | null
          postcode_district?: string | null
          postcode_full?: string | null
          postcode_sector?: string | null
          pricing_id?: string | null
          property_type?: string | null
          provenance?: Json | null
          publish_from?: string | null
          publish_until?: string | null
          raia_id?: string
          raia_schema_version?: string | null
          rent_pcm?: number | null
          service_type?: string
          snapshot_version?: number | null
          source?: string
          street_name?: string | null
          suburb?: string | null
          synced_at?: string
          total_floors?: number | null
          un_locode?: string | null
          visibility?: string
          withdrawn_at?: string | null
        }
        Relationships: []
      }
      tbl_listing_views: {
        Row: {
          anon_session_id: string | null
          external_id: string | null
          raia_id: string
          referrer: string | null
          user_id: string | null
          view_id: string
          viewed_at: string
        }
        Insert: {
          anon_session_id?: string | null
          external_id?: string | null
          raia_id: string
          referrer?: string | null
          user_id?: string | null
          view_id?: string
          viewed_at?: string
        }
        Update: {
          anon_session_id?: string | null
          external_id?: string | null
          raia_id?: string
          referrer?: string | null
          user_id?: string | null
          view_id?: string
          viewed_at?: string
        }
        Relationships: []
      }
      tbl_raia_agent_registry: {
        Row: {
          agent_card_url: string
          agent_id: string
          capabilities: string[] | null
          companies_house_number: string | null
          contact_email: string | null
          contact_phone: string | null
          created_at: string
          description: string | null
          discovered_at: string
          discovery_method: string
          display_name: string | null
          jurisdictions: string[] | null
          last_crawl_error: string | null
          last_crawl_status: string | null
          last_crawled_at: string | null
          listing_count_last: number | null
          logo_url: string | null
          name: string | null
          notes: string | null
          revoked_at: string | null
          schema_version: string | null
          trust_tier: string
          updated_at: string
          verification_status: string
        }
        Insert: {
          agent_card_url: string
          agent_id: string
          capabilities?: string[] | null
          companies_house_number?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          created_at?: string
          description?: string | null
          discovered_at?: string
          discovery_method: string
          display_name?: string | null
          jurisdictions?: string[] | null
          last_crawl_error?: string | null
          last_crawl_status?: string | null
          last_crawled_at?: string | null
          listing_count_last?: number | null
          logo_url?: string | null
          name?: string | null
          notes?: string | null
          revoked_at?: string | null
          schema_version?: string | null
          trust_tier?: string
          updated_at?: string
          verification_status?: string
        }
        Update: {
          agent_card_url?: string
          agent_id?: string
          capabilities?: string[] | null
          companies_house_number?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          created_at?: string
          description?: string | null
          discovered_at?: string
          discovery_method?: string
          display_name?: string | null
          jurisdictions?: string[] | null
          last_crawl_error?: string | null
          last_crawl_status?: string | null
          last_crawled_at?: string | null
          listing_count_last?: number | null
          logo_url?: string | null
          name?: string | null
          notes?: string | null
          revoked_at?: string | null
          schema_version?: string | null
          trust_tier?: string
          updated_at?: string
          verification_status?: string
        }
        Relationships: []
      }
      tbl_saved_searches: {
        Row: {
          alert_frequency: string | null
          created_at: string
          filters: Json
          last_run_at: string | null
          name: string
          search_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          alert_frequency?: string | null
          created_at?: string
          filters: Json
          last_run_at?: string | null
          name: string
          search_id?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          alert_frequency?: string | null
          created_at?: string
          filters?: Json
          last_run_at?: string | null
          name?: string
          search_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      tbl_users: {
        Row: {
          created_at: string
          display_name: string | null
          email: string
          id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          email: string
          id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          email?: string
          id?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      vw_raia_agent_registry_public: {
        Row: {
          agent_card_url: string | null
          agent_id: string | null
          capabilities: string[] | null
          display_name: string | null
          jurisdictions: string[] | null
          logo_url: string | null
          name: string | null
          trust_tier: string | null
          verification_status: string | null
        }
        Relationships: []
      }
    }
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
